### ISSUE TITLE
ensureSecureImageRequest cannot be set to false

### ISSUE THREAD

**Issue by kryp71c** [laurengarcia/url-metadata#16]
Hi guys,

This line in index.js will evaluate to true when 'options.ensureSecureImageRequest' is set to false:

`ensureSecureImageRequest: options.ensureSecureImageRequest || true`

**Comment by laurengarcia** [comment]
Whoops -- you are correct. Will fix.

**Comment by sidshrivastav** [comment]
Hi, I fixed the issue. Please find the [PR ](https://github.com/LevelNewsOrg/url-metadata/pull/22) for changes.

**Comment by laurengarcia** [comment]
Fixed.
