### ISSUE TITLE
warning > request@2.88.2 deprecated

### ISSUE THREAD

**Issue by ArtashMardoyan** [laurengarcia/url-metadata#23]
warning url-metadata > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning url-metadata > standard > eslint > file-entry-cache > flat-cache > circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.

**Comment by laurengarcia** [comment]
It's a pretty decent sized refactor that needs to happen to remove the `request` module. The other warning about standard is for the linter (only). 

There should be no security or other issues that either of these presents at this time. 
Will refactor when time permits. 
Thanks

**Comment by laurengarcia** [comment]
Sorry for delay, this should be fixed in version `3.0.1`
https://www.npmjs.com/package/url-metadata

Feel free to reopen if you need a backport to version `2.x.x`.
