### ISSUE TITLE
Uncaught TypeError: Cannot add property robots, object is not extensible

### ISSUE THREAD

**Issue by ivanvorona** [laurengarcia/url-metadata#25]
Hello,

First of all - Thank you for good library guys.
I am trying to run in from VueJS application mixin and getting following error:
index.js?e609:1081 Uncaught TypeError: Cannot add property robots, object is not extensible
 any idea how to workaround it?
``` const urlMetaData = require('url-metadata');

export const urlMetadata = {
  created() {

    this.urlMetaDataCall('https://cors-anywhere.herokuapp.com/http://bit.ly/2ePIrDy');
  },
        methods: {
   urlMetaDataCall(url){
     urlMetaData(url);
    
     return url;...```
thanks!

**Comment by artfurma** [comment]
Hi, 

I'm also facing the same issue. Did you manage to find a solution for this?

**Comment by ivanvorona** [comment]
Hi - No, i didn't not. if you find solution, feel free to share. I am thinking about standing up server side api as the proxy to work it around but would love to resolve it on client if possible instead.

**Comment by czarandy** [comment]
I sent https://github.com/LevelNewsOrg/url-metadata/pull/29 to fix this issue.

**Comment by laurengarcia** [comment]
#29 was merged.
