### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by presencewebdesign** [laurengarcia/url-metadata#28]
When I try to fetch meta data I get this issue, how do I resolve?

Access to fetch at 'https://chrome.google.com/' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

**Comment by laurengarcia** [comment]
Read up on CORS, there's nothing this module can do. It has to do with the response headers.
