### ISSUE TITLE
Redirect / short URLs not working

### ISSUE THREAD

**Issue by alexpluto** [laurengarcia/url-metadata#30]
Only certain short URLs that redirect are supported where meta data is returned.

e.g. https://abnb.me/fHw1T5PE68 - this is **not** working and no meaningful meta data is returned. When using this URL in: https://developers.facebook.com/tools/debug/ - you can see the meta data that should be returned after the redirect

e.g. https://bit.ly/322JENd - this is working as expected and returns meta data from the redirected URL.

**Comment by alexpluto** [comment]
@laurengarcia @suchtomwow @czarandy @ITJesse Hi all, just wondering if you ever had a chance to see this?

**Comment by abhi31AI** [comment]
@alexpluto did you find a solution for this, I am also facing this issue

**Comment by alexpluto** [comment]
@abhi31AI unfortunately not :(

**Comment by abhi31AI** [comment]
@alexpluto do you know any other alternatives to bring out the metadata from the url.

Actually URLs that I am working on, twitter, fb and linkedIn are able to get those metadata out but I am not able to do it in my web application with the given npm package

**Comment by alexpluto** [comment]
@abhi31AI unfortunately we paused investigating this further. Would love to hear if you're able to solve this!

**Comment by laurengarcia** [comment]
Looked into this, it seems there is an issue with https://abnb.me/fHw1T5PE68 where there is an intermediary hop in the request forwarding chain. The final hop where it gets stuck is: `https://bnc.lt/m/fHw1T5PE68?_p=c61229c59b1c65f0e6038ffce9`. There is no issue with the forwarding when i make the request through a browser so it may have to do with certain request headers (some companies block scraping from their front ends).

With the new version of `url-metadata` version 3.0.1  you may be able to use the custom `requestHeaders` option to get around this.
