### ISSUE TITLE
I am getting cors error when ever i hit this function

### ISSUE THREAD

**Issue by salwa1234** [laurengarcia/url-metadata#34]
Access to fetch at 'https://github.com/salwa1234/meuzmnet-react/pull/829' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

**Comment by laurengarcia** [comment]
CORS policy errors must be fixed on the server/url that you are making requests to. 
Has nothing to do with this module.

More info:
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
