### ISSUE TITLE
CORS Origin Error

### ISSUE THREAD

**Issue by Codemaine** [laurengarcia/url-metadata#35]
access to fetch at url from origin 'http://localhost:19006' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

**Comment by bilalrashid300** [comment]
@Codemaine did you find a solution for this? same problem here.

**Comment by ilhammrg** [comment]
@bilalrashid300 i tried to fetch from node environtment and it works fine.

**Comment by laurengarcia** [comment]
The newest version `3.0.1` contains an option to set custom `fetch` API mode. Default is `cors` but can be overridden as `no-cors`, `same-origin`, etc.

https://www.npmjs.com/package/url-metadata

**Comment by faithandjs** [comment]
I tried the 3 modes, it gave different errors, no metadata 

> The newest version `3.0.1` contains an option to set custom `fetch` API mode. Default is `cors` but can be overridden as `no-cors`, `same-origin`, etc.
> 
> https://www.npmjs.com/package/url-metadata

**Comment by laurengarcia** [comment]
Seems to work for everyone else. Without additional context (url, error message) this is impossible to troubleshoot.
