### ISSUE TITLE
Failed to compile with x errors . These dependencies were not found:

### ISSUE THREAD

**Issue by ShubhamVerma1811** [laurengarcia/url-metadata#39]
I am using this lib with NuxtJS + Typescript.
And this error comes up while using the `urlMetaData` function. 
I double-checked by removing the function and the error was gone.
Image for reference:
![Screenshot (612)](https://user-images.githubusercontent.com/25576658/113505009-c6827b00-9559-11eb-8a76-7b623ed5cb6e.png)

**Comment by laurengarcia** [comment]
Sorry for delay, this should be fixed in version `3.0.1`
https://www.npmjs.com/package/url-metadata

Feel free to reopen if you need a backport to version `2.x.x`.
