### ISSUE TITLE
Problems with cheerio dependency version

### ISSUE THREAD

**Issue by luisvidalintroini2** [laurengarcia/url-metadata#43]
We have detected that in some cases, the library reach a loop because css-select. This issue is already resolved on css-select. I suppose that if the library reference is update to take version 1.0 of cheerio the problem would be resolved.

**Comment by laurengarcia** [comment]
Sorry for delay, this should be fixed in version `3.0.1`
https://www.npmjs.com/package/url-metadata

Feel free to reopen if you need a backport to version `2.x.x`.
