### ISSUE TITLE
Electron error - Cannot find module 'url-metadata'

### ISSUE THREAD

**Issue by jeffery30162** [laurengarcia/url-metadata#51]
After adding module to my electron angular project i am now receiving this error shown below:

This error only occurs when building the electron and not running with serve

![image](https://user-images.githubusercontent.com/20176413/164119679-d3176da3-72fb-405e-a3f3-af7590012a36.png)

Thanks

**Comment by laurengarcia** [comment]
Sorry for delay, this should be fixed in version `3.0.1`
https://www.npmjs.com/package/url-metadata

Feel free to reopen if you need a backport to version `2.x.x`.
