### ISSUE TITLE
fetch is not defined

### ISSUE THREAD

**Issue by adnanafzal565** [laurengarcia/url-metadata#68]
Hello.

I am getting "fetch is not defined" on the following line:

`const metadata = await urlMetadata(https://adnan-tech.com)`

Any help is highly appreciated.

**Comment by laurengarcia** [comment]
You're either in a Node or browser environment that doesn't have javascript `fetch` available.
Try upgrading your environment, or you can use an earlier version of this package (version 2.5.0).

**Comment by adnanafzal565** [comment]
> Owner

Thanks. Exactly. I was using Node version 14. I updated my Node version to 20. Now it works fine. Hope it helps someone.

**Comment by adnanafzal565** [comment]
One more reason I found is that there are some websites like facebook.com, and twitter.com, where `fetch()` or `request()` modules don't work. However, it worked on other sites.

**Comment by laurengarcia** [comment]
Many of the big sites explicitly block scrapers like this intentionally.

**Comment by adnanafzal565** [comment]
> Many of the big sites explicitly block scrapers like this intentionally.

Got it.
