### ISSUE TITLE
Handling specific encodings dropped?

### ISSUE THREAD

**Issue by openminded-oscar** [laurengarcia/url-metadata#70]
The previous version 2.5.0 had a decode parameter that should be handling specific encodings. How that should be done in 3.3.0?
The problem is reproducing with windows 1251 encoding. The text is unreadable afterwards.

Thank you!

**Comment by openminded-oscar** [comment]
The problem is reproducing with windows 1251 encoding. The text is unreadable afterwards.

**Comment by openminded-oscar** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Response/text

**Comment by laurengarcia** [comment]
Thanks for your note. I actually removed it for version >3.0 just to simplify the api because i thought nobody used it but me; almost nobody ever brought it up here all those years. So, I am happy to add it back into a new release. Give me a few days. Sorry about that.

**Comment by openminded-oscar** [comment]
Thank you! Would be great!

**Comment by openminded-oscar** [comment]
What I was thinking is like this:
```
return fetch(url, requestOpts)
    .then((response) => {
      if (!response.ok) {
        throw new Error(`response code ${response.status}`);
      }

      // rewrite url if our request had to follow redirects to resolve the
      // final link destination (for example: links shortened by bit.ly)
      if (response.url) url = response.url;

      const contentType = response.headers.get('content-type');
      const isText = contentType && contentType.startsWith('text');
      const isHTML = contentType && contentType.includes('html');
      // extract charset, depends on iconv
      const charsetExtracted = extractCharset(contentType);
      const charset = (charsetExtracted && iconv.encodingExists(charsetExtracted))? charsetExtracted: 'UTF-8';

      if (!isText || !isHTML) {
        throw new Error(`unsupported content type: ${contentType}`);
      }

      return response.arrayBuffer()
        .then(buffer => iconv.decode(Buffer.from(buffer), charset, {defaultEncoding: 'UTF-8'}));
    })
    .then((body) => {
      return parse(url, body, opts);
    });
}

function extractCharset(contentType) {
  const charsetRegex = /charset=([^\s;]+)/;
  const match = contentType.match(charsetRegex);

  if (match && match[1]) {
    return match[1];
  } else {
    return null;
  }
}
```

**Comment by laurengarcia** [comment]
Version 3.4.0 is in production supports this now: https://www.npmjs.com/package/url-metadata
Implementation details here: https://github.com/laurengarcia/url-metadata/pull/72

**Comment by laurengarcia** [comment]
Tightened up the lib/extract-charset.js regexes, check the latest on `master`.
