### ISSUE TITLE
Typescript definition is missing `parseResponseObject`

### ISSUE THREAD

**Issue by ajmas** [laurengarcia/url-metadata#76]
Looking at the Typescript definition, it would appear that `parseResponseObject` is missing from the `Options` interface, causing problems when compiling in Typescript. 

This issue can be worked around by casting the options to `any`.

url-metadata: 3.5.2

**Comment by laurengarcia** [comment]
Thanks for filing this bug. Should be fixed in latest version 3.5.3
https://www.npmjs.com/package/url-metadata

Feel free to reopen if you have any further issues.
