### ISSUE TITLE
First parameter can't be null in typescript

### ISSUE THREAD

**Issue by ajmas** [laurengarcia/url-metadata#81]
I just got the latest version of `url-metadata` and tried the following code

```ts
const response = new Response(html);
const metadata = await urlMetadata(null, {
  requestHeaders: {
    ...(this.requestHeaders || {}),
    'Accept-Language': locale,
  },
  parseResponseObject: response
});    
```

VSCode is telling me `Argument of type 'null' is not assignable to parameter of type 'string'`. For now I can work around this by using `null as any`, but it isn't ideal.

One way of addressing this is with:

```ts
declare function urlMetadata(
  url: string | null,
  options?: urlMetadata.Options,
): Promise<urlMetadata.Result>
```

The may be some way of indicating `null` is only permitted when `parseResponseObject` is provided, but I'd have to explore, since my TS knowledge doesn't go that deep.

**Comment by laurengarcia** [comment]
Thanks for catching that. Strangely my editor didn't say anything, nor did the Typescript/ Parcel compiler i added to /example-typescript dir either. Sorry for the oversight. 

New version 3.5.6 has the bugfix.
https://www.npmjs.com/package/url-metadata
