### ISSUE TITLE
Encoded favicon URL gives 404

### ISSUE THREAD

**Issue by MartinMalinda** [laurengarcia/url-metadata#86]
When I'm loading url like this one https://goout.net/cs/colours-of-ostrava-2024/szqghcw/. I'm getting favicon URL https://goout.net/apple-touch-icon-144x144.png%3Fv=1.0 which gives 404 because correct url is https://goout.net/apple-touch-icon-144x144.png?v=1.0.

In the HTML response of the site it's fine, so the url encoding is being done sometime later. Maybe some parsing library is doing this.

**Comment by MartinMalinda** [comment]
Nevermind. If I run `url-metadata` locally as part of the test suite it works well. For some reason it behaves differently in Netlify function for me.

**Comment by laurengarcia** [comment]
Good to know.
